[project]
name = "hh-mnist"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "tqdm>=4.67.1",
  "datasets==2.18.0",
  "huggingface-hub==0.33.4",
  "fsspec==2024.2.0",
  "torch>=2.7.1",
  "transformers>=4.51.0",
  "peft>=0.13.2",
]
